### ISSUE TITLE
无法正常执行system("xxx");

### ISSUE THREAD

**Issue by w0odpeck3r** [giantbranch/pwn_deploy_chroot#3]
https://github.com/giantbranch/pwn_deploy_chroot/blob/d86586b0d23a52193eca74efce0475561c484f28/initialize.py#L124

这里有bug，应该先在前面mkdir一个/home/%s/bin,再在这里cp xxx /home/%s/bin/.
否则只会cp过去一个名叫bin的cat二进制文件，导致system无法正常执行

**Comment by giantbranch** [comment]
我是用最新git clone下来的代码重新build，我这边没有问题
![image](https://user-images.githubusercontent.com/7982908/65739611-80548c00-e118-11e9-93c3-21091fdb4a2b.png)

↑↑↑↑↑↑上面的图片可能显示不出来，githubusercontent.com可能需要翻墙，也下面给出图片链接：

https://user-images.githubusercontent.com/7982908/65739611-80548c00-e118-11e9-93c3-21091fdb4a2b.png

因为就算关闭替换/bin/sh，Dockerfile里面还是生成了下面代码

```
# copy bin
COPY ./bin/pwn1 /home/pwn1/pwn1
COPY ./catflag /home/pwn1/bin/sh
COPY ./bin/pwn1_copy1 /home/pwn1_copy1/pwn1_copy1
COPY ./catflag /home/pwn1_copy1/bin/sh
COPY ./bin/pwn1_copy2 /home/pwn1_copy2/pwn1_copy2
COPY ./catflag /home/pwn1_copy2/bin/sh
```

而在`COPY ./catflag /home/pwn1/bin/sh`的时候，docker自动就帮你把目录建好了

假如关闭了替换/bin/sh，接下里的Dockerfile中的`cp /bin/sh /home/XXX/bin`会重新覆盖catflag为真正的/bin/sh

**Comment by w0odpeck3r** [comment]
了解了 是我魔改禁止cp catflag的问题 感谢
