### ISSUE TITLE
自带so文件的题目部署

### ISSUE THREAD

**Issue by raddyfiy** [giantbranch/pwn_deploy_chroot#6]
有的题目给了指定版本的libc.so文件，可否支持这种部署呢？
例如代码可以这样：如果在bin里发现了文件夹，则部署文件夹里的程序，并加载同目录的so文件。不知道大牛有意向支持这种的功能不

**Comment by giantbranch** [comment]
你可以尝试修改config中的XINETD，加入env，设置LD_LIBRARY_PATH的值试试

文档：https://manned.org/xinetd.conf/95ffded3
